### ISSUE TITLE
Default export snippet doesnt work in .js file

### ISSUE THREAD

**Issue by horaklukas** [AckeeCZ/vscode-frontend#2]
Since `ed` (default export) snippet is defined in `javascriptreact.json` it's not suggested in files with javascript (not javascript react) syntax which are all with `.js` extension.

Easy fix is duplicate the snippet in `javascript.json`, but we should find (or invent 🙂) solution for sharing snippets across syntaxes.

**Comment by jstorm31** [comment]
I've added it to `javascript.json` in #5 . A way for sharing snippets between syntaxes would be great, but I don't know if it is possible. 🤔
