### ISSUE TITLE
Add create component command

### ISSUE THREAD

**Issue by horaklukas** [AckeeCZ/vscode-frontend#3]
Would be nice to have a command for generatig new react component.

My suggestion of how it should works is:

* I have a focus somewhere in files hirearchy
* Open command pallete (Cmd+ Shift + P on Mac) and select "Create component" command
* Prompt for enter a component name is opened, I type the name and confirm by press of Enter
* In the place I have a focus is created a folder with sources, eg. if I've typed a component name LoginButton, these new files appear there
   ```
  LoginButton/
      index.js
      LoginButton.jsx
      LoginButton.style.js
   ```

**Comment by horaklukas** [comment]
@cermakjiri @baierjak @jancama2 If you had another suggestions of how it should works or other tips, please don't hesitate to write them into comments 🙂

**Comment by cermakjiri** [comment]
I agree, just would rename the `LoginButton.style.js` to `LoginButton.styles.js`. The plural encourage to write named exports instead one default one.

**Comment by jstorm31** [comment]
I've opened a PR #7 where I implement this.

Unfortunately, right now it is only possible with a right-click on a folder and selecting "Ackee: create component" command. See readme in the PR where I explain it (TLDR: problem is getting folder relative path via VS Code API).
